
// Auto-generated by watch-routes.ts
type ExtractRouteParams<T> = T extends `${infer _Start}:${infer Param}/${infer Rest}`
	? { [k in Param | keyof ExtractRouteParams<Rest>]: string }
	: T extends `${infer _Start}:${infer Param}`
		? { [k in Param]: string }
		: { [k in string]: string };
type ExtractSearchParams<P> = P extends `${infer _Start}?${infer Search}`
	? { [k in Search]: string }
	: { [k in string]: string };

declare global {
type ClientRoutePath = "/note" | "/profile" | "/register" | "/login" | "/note/:id" | "/change-password" | "/verify-email" | "/forgot-password" | "/";
type ClientRoutePathParam<P extends ClientRoutePath> = ExtractRouteParams<P>;
type ClientRouteSearchParam<P extends ClientRoutePath> = ExtractSearchParams<P>;

type ServerRoutePath = "/api/note/update/:id" | "/api/auth/verify-email" | "/api/auth/profile" | "/api/auth/change-password" | "/api/auth/register" | "/api/auth/forgot-password" | "/api/note/create" | "/api/note/all" | "/api/auth/login" | "/api/note/:id" | "/api/auth/logout" | "/api/auth/verify-email-resend";
type ServerRoutePathParam<P extends ServerRoutePath> = ExtractRouteParams<P>;
type ServerRouteSearchParam<P extends ServerRoutePath> = ExtractSearchParams<P>;
}

export const clientRoutePaths:ClientRoutePath[] = ["/note","/profile","/register","/login","/note/:id","/change-password","/verify-email","/forgot-password","/"];
export const serverRoutePaths:ServerRoutePath[] = ["/api/note/update/:id","/api/auth/verify-email","/api/auth/profile","/api/auth/change-password","/api/auth/register","/api/auth/forgot-password","/api/note/create","/api/note/all","/api/auth/login","/api/note/:id","/api/auth/logout","/api/auth/verify-email-resend"];